//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCenterNotesApp.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountTB
    {
        public string UserName { get; set; }
        public string UserPass { get; set; }
        public string Type { get; set; }
        public string IsOnline { get; set; }
        public int Uid { get; set; }
    }
}
