//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCenterNotesApp.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoteAttachment
    {
        public int NoteAttachmentsID { get; set; }
        public string NoteAttachmentsName { get; set; }
        public string NoteAttachmentsPath { get; set; }
        public Nullable<int> NoteID { get; set; }
        public bool IsDeleted { get; set; }
    }
}
