//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCenterNotesApp.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineApprovals_AttachmentTypeDIM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OnlineApprovals_AttachmentTypeDIM()
        {
            this.OnlineApprovals_RequestAttachment = new HashSet<OnlineApprovals_RequestAttachment>();
        }
    
        public int AttachmentTypeID { get; set; }
        public string AttachmentTypeName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OnlineApprovals_RequestAttachment> OnlineApprovals_RequestAttachment { get; set; }
    }
}
