//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BNC.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Provider()
        {
            this.ProviderContacts = new HashSet<ProviderContact>();
            this.ReceivingRequests = new HashSet<ReceivingRequest>();
        }
    
        public int ProviderID { get; set; }
        public string ProviderEnglishName { get; set; }
        public string ProviderArabicName { get; set; }
        public int MCAProviderPin { get; set; }
        public int IbnSinaProviderPin { get; set; }
        public int ProviderTypeFK { get; set; }
        public Nullable<int> GovernmentFK { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<bool> IsMain { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> StoppedDate { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public Nullable<System.DateTime> DeletionDate { get; set; }
    
        public virtual GovernmentDIM GovernmentDIM { get; set; }
        public virtual ProviderTypeDIM ProviderTypeDIM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProviderContact> ProviderContacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceivingRequest> ReceivingRequests { get; set; }
    }
}
