//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PhNetworkEntities : DbContext
    {
        public PhNetworkEntities()
            : base("name=PhNetworkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CallCenterAppUser> CallCenterAppUsers { get; set; }
        public DbSet<ColorAlert> ColorAlerts { get; set; }
        public DbSet<EmailApprovalRequest> EmailApprovalRequests { get; set; }
        public DbSet<EmailApprovalsConfiguration> EmailApprovalsConfigurations { get; set; }
        public DbSet<EmailRequestAttachmentsDetail> EmailRequestAttachmentsDetails { get; set; }
        public DbSet<EmailRequestMailingDetail> EmailRequestMailingDetails { get; set; }
        public DbSet<EmailRequestStatusDIM> EmailRequestStatusDIMs { get; set; }
        public DbSet<TicketType> TicketTypes { get; set; }
    }
}
