//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket_Details
    {
        public int TicketDetails_ID { get; set; }
        public Nullable<int> Ticket_ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Notes { get; set; }
        public Nullable<int> User_ID { get; set; }
        public string Seen_By_User { get; set; }
        public string Seen_By_IT { get; set; }
    }
}
