//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int User_ID { get; set; }
        public string User_Name { get; set; }
        public string Password { get; set; }
        public Nullable<int> Dept_ID { get; set; }
        public Nullable<int> Sub_Dept_ID { get; set; }
        public string E_mail { get; set; }
        public string User_Status { get; set; }
    }
}
