//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogsDetail
    {
        public int LogID { get; set; }
        public Nullable<int> RequestFK { get; set; }
        public Nullable<int> LogTypeFK { get; set; }
        public Nullable<int> UserFK { get; set; }
        public Nullable<System.DateTime> LogTime { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public string UserName { get; set; }
        public string Comment { get; set; }
    
        public virtual LogTypeDIM LogTypeDIM { get; set; }
        public virtual Request Request { get; set; }
        public virtual User User { get; set; }
    }
}
