//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hr_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyReport
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string RequestStatus { get; set; }
        public string MyTeamLeader { get; set; }
        public string MySupervisor { get; set; }
        public string MyManager { get; set; }
        public string MyManagerBackup { get; set; }
        public string DailyWork { get; set; }
        public string TeamLeaderApproved { get; set; }
        public string SupervisorApproved { get; set; }
        public string MyManagerBackupApproval { get; set; }
        public string ManagerApproved { get; set; }
        public Nullable<System.DateTime> TeamLeaderApprovalTime { get; set; }
        public Nullable<System.DateTime> SuppervisorApprovedOn { get; set; }
        public Nullable<System.DateTime> MyManagerBackupApprovedOn { get; set; }
        public Nullable<System.DateTime> ManagerApprovalTime { get; set; }
        public string EmpType { get; set; }
        public Nullable<System.DateTime> Day { get; set; }
        public string Department { get; set; }
        public string Managment { get; set; }
    }
}
