// <auto-generated />
namespace WarhouseSystem.DB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addModule1DB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addModule1DB));
        
        string IMigrationMetadata.Id
        {
            get { return "202001241822358_addModule1DB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
