//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CypressPendingRequestsReminder.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApprovalFlowDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ApprovalFlowDetail()
        {
            this.ApprovalFlowRequestDetails = new HashSet<ApprovalFlowRequestDetail>();
            this.ApprovalFlowUserDetails = new HashSet<ApprovalFlowUserDetail>();
        }
    
        public int ApprovalFlowDetailsID { get; set; }
        public bool IsDirectManager { get; set; }
        public bool IsTeamManager { get; set; }
        public int Order { get; set; }
        public int ApprovalFlowFK { get; set; }
        public Nullable<int> LeaveTypeFK { get; set; }
        public Nullable<int> ApprovalFlowPersonFK { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public Nullable<System.DateTime> DeletionDate { get; set; }
    
        public virtual ApprovalFlow ApprovalFlow { get; set; }
        public virtual LeaveType LeaveType { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApprovalFlowRequestDetail> ApprovalFlowRequestDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApprovalFlowUserDetail> ApprovalFlowUserDetails { get; set; }
    }
}
