//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddAcccuralLeaveTypesForNewEmployees_WS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.ApprovalFlowRequestDetails = new HashSet<ApprovalFlowRequestDetail>();
            this.LogsDetails = new HashSet<LogsDetail>();
            this.RequestDetails = new HashSet<RequestDetail>();
            this.RequestHandlers = new HashSet<RequestHandler>();
            this.RequestHistories = new HashSet<RequestHistory>();
            this.RequestHoursHandlers = new HashSet<RequestHoursHandler>();
            this.UserEntitlementChanges = new HashSet<UserEntitlementChange>();
            this.ServicesLogs = new HashSet<ServicesLog>();
        }
    
        public int RequestID { get; set; }
        public int Order { get; set; }
        public Nullable<int> LeaveTypeFK { get; set; }
        public Nullable<int> UserFK { get; set; }
        public Nullable<int> RequesStatusFK { get; set; }
        public System.DateTime DurationFrom { get; set; }
        public System.DateTime DurationTo { get; set; }
        public System.DateTime BackToWork { get; set; }
        public decimal RequestDuration { get; set; }
        public Nullable<int> Level { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public Nullable<System.DateTime> DeletionDate { get; set; }
        public Nullable<int> LeaveDurationUnitFK { get; set; }
        public Nullable<int> PartialDurationUnitFK { get; set; }
        public Nullable<int> Substitute { get; set; }
        public string Reason { get; set; }
        public string Comment { get; set; }
        public Nullable<int> OnBehalfOfRequesterID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApprovalFlowRequestDetail> ApprovalFlowRequestDetails { get; set; }
        public virtual LeaveTypePartialDurationUnitDIM LeaveTypePartialDurationUnitDIM { get; set; }
        public virtual LeaveType LeaveType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogsDetail> LogsDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestDetail> RequestDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestHandler> RequestHandlers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestHistory> RequestHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestHoursHandler> RequestHoursHandlers { get; set; }
        public virtual RequestStatu RequestStatu { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserEntitlementChange> UserEntitlementChanges { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicesLog> ServicesLogs { get; set; }
    }
}
