//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PhMobAppEntities : DbContext
    {
        public PhMobAppEntities()
            : base("name=PhMobAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AccountTB> AccountTBs { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<Complaint> Complaints { get; set; }
        public DbSet<DoctorTB> DoctorTBs { get; set; }
        public DbSet<HospitalTB> HospitalTBs { get; set; }
        public DbSet<LaboratoryTB> LaboratoryTBs { get; set; }
        public DbSet<LocationsTB> LocationsTBs { get; set; }
        public DbSet<Loginer> Loginers { get; set; }
        public DbSet<Medicalid> Medicalids { get; set; }
        public DbSet<NewsFeed> NewsFeeds { get; set; }
        public DbSet<PharmacyTB> PharmacyTBs { get; set; }
        public DbSet<pic> pics { get; set; }
        public DbSet<SubLocatiobTB> SubLocatiobTBs { get; set; }
        public DbSet<WebsiteAccount> WebsiteAccounts { get; set; }
        public DbSet<ClaimsApproval> ClaimsApprovals { get; set; }
        public DbSet<Feedback> Feedbacks { get; set; }
        public DbSet<CallCenterAppUser> CallCenterAppUsers { get; set; }
        public DbSet<ClientNote> ClientNotes { get; set; }
        public DbSet<ProviderAppUser> ProviderAppUsers { get; set; }
        public DbSet<CallCenterEmailApproval> CallCenterEmailApprovals { get; set; }
        public DbSet<OpticalTB> OpticalTBs { get; set; }
    }
}
