//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineApprovals.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineApprovals_RequestDetailsTypeDIM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OnlineApprovals_RequestDetailsTypeDIM()
        {
            this.OnlineApprovals_RequestDetails = new HashSet<OnlineApprovals_RequestDetails>();
        }
    
        public int RequestDetailsTypeID { get; set; }
        public string RequestDetailsTypeName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OnlineApprovals_RequestDetails> OnlineApprovals_RequestDetails { get; set; }
    }
}
