//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineApprovals.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PhNetworkEntities : DbContext
    {
        public PhNetworkEntities()
            : base("name=PhNetworkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CallCenterAppUser> CallCenterAppUsers { get; set; }
        public virtual DbSet<OnlineApprovals_AttachmentTypeDIM> OnlineApprovals_AttachmentTypeDIM { get; set; }
        public virtual DbSet<OnlineApprovals_Configrations> OnlineApprovals_Configrations { get; set; }
        public virtual DbSet<OnlineApprovals_DemandedDrugsDetails> OnlineApprovals_DemandedDrugsDetails { get; set; }
        public virtual DbSet<OnlineApprovals_DrugsListDIM> OnlineApprovals_DrugsListDIM { get; set; }
        public virtual DbSet<OnlineApprovals_FailedTransactions> OnlineApprovals_FailedTransactions { get; set; }
        public virtual DbSet<OnlineApprovals_Inovices> OnlineApprovals_Inovices { get; set; }
        public virtual DbSet<OnlineApprovals_LoginKeys> OnlineApprovals_LoginKeys { get; set; }
        public virtual DbSet<OnlineApprovals_LogsDetails> OnlineApprovals_LogsDetails { get; set; }
        public virtual DbSet<OnlineApprovals_LogTypeDIM> OnlineApprovals_LogTypeDIM { get; set; }
        public virtual DbSet<OnlineApprovals_ProviderTypeDIM> OnlineApprovals_ProviderTypeDIM { get; set; }
        public virtual DbSet<OnlineApprovals_RequestAttachment> OnlineApprovals_RequestAttachment { get; set; }
        public virtual DbSet<OnlineApprovals_RequestDetails> OnlineApprovals_RequestDetails { get; set; }
        public virtual DbSet<OnlineApprovals_RequestDetailsTypeDIM> OnlineApprovals_RequestDetailsTypeDIM { get; set; }
        public virtual DbSet<OnlineApprovals_RequestStatusDIM> OnlineApprovals_RequestStatusDIM { get; set; }
        public virtual DbSet<PharmacyTB> PharmacyTBs { get; set; }
        public virtual DbSet<OnlineApprovals_RequestTypeDIM> OnlineApprovals_RequestTypeDIM { get; set; }
        public virtual DbSet<OnlineApprovals_Requests> OnlineApprovals_Requests { get; set; }
    
        public virtual ObjectResult<Nullable<int>> SP_MyOnlineApprovals_CountRequestsByStatus(Nullable<int> statusID, string doctorAssignee)
        {
            var statusIDParameter = statusID.HasValue ?
                new ObjectParameter("StatusID", statusID) :
                new ObjectParameter("StatusID", typeof(int));
    
            var doctorAssigneeParameter = doctorAssignee != null ?
                new ObjectParameter("DoctorAssignee", doctorAssignee) :
                new ObjectParameter("DoctorAssignee", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_MyOnlineApprovals_CountRequestsByStatus", statusIDParameter, doctorAssigneeParameter);
        }
    
        public virtual ObjectResult<SP_MyOnlineApprovals_RequestsByStatus_Result> SP_MyOnlineApprovals_RequestsByStatus(Nullable<int> statusID, string doctorAssignee)
        {
            var statusIDParameter = statusID.HasValue ?
                new ObjectParameter("StatusID", statusID) :
                new ObjectParameter("StatusID", typeof(int));
    
            var doctorAssigneeParameter = doctorAssignee != null ?
                new ObjectParameter("DoctorAssignee", doctorAssignee) :
                new ObjectParameter("DoctorAssignee", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MyOnlineApprovals_RequestsByStatus_Result>("SP_MyOnlineApprovals_RequestsByStatus", statusIDParameter, doctorAssigneeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_OnlineApprovals_ClaimsPerCurrentMonth(Nullable<int> providerID)
        {
            var providerIDParameter = providerID.HasValue ?
                new ObjectParameter("providerID", providerID) :
                new ObjectParameter("providerID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_OnlineApprovals_ClaimsPerCurrentMonth", providerIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_OnlineApprovals_CountRequestsByStatus(Nullable<int> statusID)
        {
            var statusIDParameter = statusID.HasValue ?
                new ObjectParameter("StatusID", statusID) :
                new ObjectParameter("StatusID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_OnlineApprovals_CountRequestsByStatus", statusIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_OnlineApprovals_CountRequestsByStatusAndProvider(Nullable<int> providerID, Nullable<int> statusID)
        {
            var providerIDParameter = providerID.HasValue ?
                new ObjectParameter("providerID", providerID) :
                new ObjectParameter("providerID", typeof(int));
    
            var statusIDParameter = statusID.HasValue ?
                new ObjectParameter("StatusID", statusID) :
                new ObjectParameter("StatusID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_OnlineApprovals_CountRequestsByStatusAndProvider", providerIDParameter, statusIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_OnlineApprovals_CountTotalRequestsByProviderID(Nullable<int> providerID)
        {
            var providerIDParameter = providerID.HasValue ?
                new ObjectParameter("providerID", providerID) :
                new ObjectParameter("providerID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_OnlineApprovals_CountTotalRequestsByProviderID", providerIDParameter);
        }
    
        public virtual ObjectResult<SP_OnlineApprovals_InovicesByInvoiceID_Result> SP_OnlineApprovals_InovicesByInvoiceID(Nullable<int> invoiceID)
        {
            var invoiceIDParameter = invoiceID.HasValue ?
                new ObjectParameter("InvoiceID", invoiceID) :
                new ObjectParameter("InvoiceID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_OnlineApprovals_InovicesByInvoiceID_Result>("SP_OnlineApprovals_InovicesByInvoiceID", invoiceIDParameter);
        }
    
        public virtual ObjectResult<SP_OnlineApprovals_InovicesByMedicalID_Result> SP_OnlineApprovals_InovicesByMedicalID(Nullable<int> medicalID)
        {
            var medicalIDParameter = medicalID.HasValue ?
                new ObjectParameter("MedicalID", medicalID) :
                new ObjectParameter("MedicalID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_OnlineApprovals_InovicesByMedicalID_Result>("SP_OnlineApprovals_InovicesByMedicalID", medicalIDParameter);
        }
    
        public virtual ObjectResult<SP_OnlineApprovals_InovicesByRequestID_Result> SP_OnlineApprovals_InovicesByRequestID(Nullable<int> requestID)
        {
            var requestIDParameter = requestID.HasValue ?
                new ObjectParameter("RequestID", requestID) :
                new ObjectParameter("RequestID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_OnlineApprovals_InovicesByRequestID_Result>("SP_OnlineApprovals_InovicesByRequestID", requestIDParameter);
        }
    
        public virtual ObjectResult<SP_OnlineApprovals_RequestsByprovider_Result> SP_OnlineApprovals_RequestsByprovider(Nullable<int> providerID)
        {
            var providerIDParameter = providerID.HasValue ?
                new ObjectParameter("providerID", providerID) :
                new ObjectParameter("providerID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_OnlineApprovals_RequestsByprovider_Result>("SP_OnlineApprovals_RequestsByprovider", providerIDParameter);
        }
    
        public virtual ObjectResult<SP_OnlineApprovals_RequestsByStatus_Result> SP_OnlineApprovals_RequestsByStatus(Nullable<int> statusID)
        {
            var statusIDParameter = statusID.HasValue ?
                new ObjectParameter("StatusID", statusID) :
                new ObjectParameter("StatusID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_OnlineApprovals_RequestsByStatus_Result>("SP_OnlineApprovals_RequestsByStatus", statusIDParameter);
        }
    
        public virtual ObjectResult<SP_OnlineApprovals_RequestsByStatusAndProvider_Result> SP_OnlineApprovals_RequestsByStatusAndProvider(Nullable<int> providerID, Nullable<int> statusID)
        {
            var providerIDParameter = providerID.HasValue ?
                new ObjectParameter("providerID", providerID) :
                new ObjectParameter("providerID", typeof(int));
    
            var statusIDParameter = statusID.HasValue ?
                new ObjectParameter("StatusID", statusID) :
                new ObjectParameter("StatusID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_OnlineApprovals_RequestsByStatusAndProvider_Result>("SP_OnlineApprovals_RequestsByStatusAndProvider", providerIDParameter, statusIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_OnlineApprovals_Total_Members(Nullable<int> providerID)
        {
            var providerIDParameter = providerID.HasValue ?
                new ObjectParameter("providerID", providerID) :
                new ObjectParameter("providerID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_OnlineApprovals_Total_Members", providerIDParameter);
        }
    
        public virtual ObjectResult<SP_OnlineApprovalsSearch_Result> SP_OnlineApprovalsSearch(string memberName, string clientName, string claimNumber, string diagnose, string requestCreationTime, string closeTime, string iVRNumber, string requestTypeID, string requestStatusID, string drugName)
        {
            var memberNameParameter = memberName != null ?
                new ObjectParameter("MemberName", memberName) :
                new ObjectParameter("MemberName", typeof(string));
    
            var clientNameParameter = clientName != null ?
                new ObjectParameter("ClientName", clientName) :
                new ObjectParameter("ClientName", typeof(string));
    
            var claimNumberParameter = claimNumber != null ?
                new ObjectParameter("ClaimNumber", claimNumber) :
                new ObjectParameter("ClaimNumber", typeof(string));
    
            var diagnoseParameter = diagnose != null ?
                new ObjectParameter("Diagnose", diagnose) :
                new ObjectParameter("Diagnose", typeof(string));
    
            var requestCreationTimeParameter = requestCreationTime != null ?
                new ObjectParameter("RequestCreationTime", requestCreationTime) :
                new ObjectParameter("RequestCreationTime", typeof(string));
    
            var closeTimeParameter = closeTime != null ?
                new ObjectParameter("CloseTime", closeTime) :
                new ObjectParameter("CloseTime", typeof(string));
    
            var iVRNumberParameter = iVRNumber != null ?
                new ObjectParameter("IVRNumber", iVRNumber) :
                new ObjectParameter("IVRNumber", typeof(string));
    
            var requestTypeIDParameter = requestTypeID != null ?
                new ObjectParameter("RequestTypeID", requestTypeID) :
                new ObjectParameter("RequestTypeID", typeof(string));
    
            var requestStatusIDParameter = requestStatusID != null ?
                new ObjectParameter("RequestStatusID", requestStatusID) :
                new ObjectParameter("RequestStatusID", typeof(string));
    
            var drugNameParameter = drugName != null ?
                new ObjectParameter("DrugName", drugName) :
                new ObjectParameter("DrugName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_OnlineApprovalsSearch_Result>("SP_OnlineApprovalsSearch", memberNameParameter, clientNameParameter, claimNumberParameter, diagnoseParameter, requestCreationTimeParameter, closeTimeParameter, iVRNumberParameter, requestTypeIDParameter, requestStatusIDParameter, drugNameParameter);
        }
    
        public virtual ObjectResult<SP_Select_OnlineApprovalByAccountID_Result> SP_Select_OnlineApprovalByAccountID(string accountName)
        {
            var accountNameParameter = accountName != null ?
                new ObjectParameter("AccountName", accountName) :
                new ObjectParameter("AccountName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Select_OnlineApprovalByAccountID_Result>("SP_Select_OnlineApprovalByAccountID", accountNameParameter);
        }
    
        public virtual ObjectResult<SP_Select_OnlineApprovalsAttachment_Result> SP_Select_OnlineApprovalsAttachment(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Select_OnlineApprovalsAttachment_Result>("SP_Select_OnlineApprovalsAttachment", iDParameter);
        }
    
        public virtual ObjectResult<SP_Select_OnlineApprovalsDemandDrugs_Result> SP_Select_OnlineApprovalsDemandDrugs(Nullable<int> requestID)
        {
            var requestIDParameter = requestID.HasValue ?
                new ObjectParameter("RequestID", requestID) :
                new ObjectParameter("RequestID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Select_OnlineApprovalsDemandDrugs_Result>("SP_Select_OnlineApprovalsDemandDrugs", requestIDParameter);
        }
    
        public virtual ObjectResult<SP_Select_OnlineApprovalsDrugList_Result> SP_Select_OnlineApprovalsDrugList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Select_OnlineApprovalsDrugList_Result>("SP_Select_OnlineApprovalsDrugList");
        }
    
        public virtual ObjectResult<SP_Select_OnlineApprovalsProvidersByID_Result> SP_Select_OnlineApprovalsProvidersByID(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Select_OnlineApprovalsProvidersByID_Result>("SP_Select_OnlineApprovalsProvidersByID", iDParameter);
        }
    
        public virtual ObjectResult<SP_Select_OnlineApprovalsRequestDetails_Result> SP_Select_OnlineApprovalsRequestDetails(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Select_OnlineApprovalsRequestDetails_Result>("SP_Select_OnlineApprovalsRequestDetails", iDParameter);
        }
    
        public virtual ObjectResult<SP_Select_OnlineApprovalsRequests_Result> SP_Select_OnlineApprovalsRequests(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Select_OnlineApprovalsRequests_Result>("SP_Select_OnlineApprovalsRequests", iDParameter);
        }
    
        public virtual ObjectResult<SP_Provider_Login_Result> SP_Provider_Login(string accountID, string password)
        {
            var accountIDParameter = accountID != null ?
                new ObjectParameter("AccountID", accountID) :
                new ObjectParameter("AccountID", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Provider_Login_Result>("SP_Provider_Login", accountIDParameter, passwordParameter);
        }
    }
}
