//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineApprovals.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineApprovals_DrugsListDIM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OnlineApprovals_DrugsListDIM()
        {
            this.OnlineApprovals_DemandedDrugsDetails = new HashSet<OnlineApprovals_DemandedDrugsDetails>();
        }
    
        public int DrugID { get; set; }
        public string DrugName { get; set; }
        public string Quaninty { get; set; }
        public int UnitQuaninty { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OnlineApprovals_DemandedDrugsDetails> OnlineApprovals_DemandedDrugsDetails { get; set; }
    }
}
