//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineApprovals.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineApprovals_LoginKeys
    {
        public int ID { get; set; }
        public int ProviderID { get; set; }
        public string ProviderKey { get; set; }
        public bool IsActive { get; set; }
        public int ProviderTypeID { get; set; }
        public System.DateTime GenerationTime { get; set; }
    
        public virtual OnlineApprovals_ProviderTypeDIM OnlineApprovals_ProviderTypeDIM { get; set; }
        public virtual PharmacyTB PharmacyTB { get; set; }
    }
}
