using CallCenterNotesApp.DLL;
using Microsoft.Exchange.WebServices.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CallCenterNotesApp.BLL
{
    public class UpdateEmailAsRead
    {

        public static bool AutoGeneratedEmailTracking(string AutoGeneratedEmailId, int? CallCenterMailType, bool IsClosed)
        {
            try
            {
                ExchangeService service = new ExchangeService();
                service.UseDefaultCredentials = false;
                FolderId SharedMailbox;
                ItemView itemView;
                using (PhNetworkEntities DbContext = new PhNetworkEntities())
                {
                    if (CallCenterMailType == 1)
                    {
                        string GeneralUserName = DbContext.EmailApprovalsConfigurations.Where(p => p.ConfigurationKey == "GeneralEmailUserName").FirstOrDefault().ConfigurationValue;
                        string GeneralPassword = DbContext.EmailApprovalsConfigurations.Where(p => p.ConfigurationKey == "GeneralEmailPassword").FirstOrDefault().ConfigurationValue;
                        string GeneralDomain = DbContext.EmailApprovalsConfigurations.Where(p => p.ConfigurationKey == "GeneralEmailDomain").FirstOrDefault().ConfigurationValue;
                        string GeneralAutodiscoverUrl = DbContext.EmailApprovalsConfigurations.Where(p => p.ConfigurationKey == "GeneralAutoDiscoverUrl").FirstOrDefault().ConfigurationValue;
                        string GeneralEmail = DbContext.EmailApprovalsConfigurations.Where(p => p.ConfigurationKey == "GeneralCallCenterEmail").FirstOrDefault().ConfigurationValue;
                        service.Credentials = new WebCredentials(GeneralUserName, GeneralPassword, GeneralDomain);
                        service.UseDefaultCredentials = false;
                        service.AutodiscoverUrl(GeneralAutodiscoverUrl);
                        SharedMailbox = new FolderId(WellKnownFolderName.Inbox, GeneralEmail);
                        itemView = new ItemView(Convert.ToInt32(DbContext.EmailApprovalsConfigurations.Where(p => p.ConfigurationKey == "GeneralEmailCount").FirstOrDefault().ConfigurationValue));
                    }
                    else if(CallCenterMailType==2)
                    {
                        string SPUserName = DbContext.EmailApprovalsConfigurations.Where(p => p.ConfigurationKey == "SPEmailUserName").FirstOrDefault().ConfigurationValue;
                        string SPPassword = DbContext.EmailApprovalsConfigurations.Where(p => p.ConfigurationKey == "SPEmailPassword").FirstOrDefault().ConfigurationValue;
                        string SPDomain = DbContext.EmailApprovalsConfigurations.Where(p => p.ConfigurationKey == "SPEmailDomain").FirstOrDefault().ConfigurationValue;
                        string SPAutodiscoverUrl = DbContext.EmailApprovalsConfigurations.Where(p => p.ConfigurationKey == "SPAutoDiscoverUrl").FirstOrDefault().ConfigurationValue;
                        string SPEmail = DbContext.EmailApprovalsConfigurations.Where(p => p.ConfigurationKey == "SPCallCenterEmail").FirstOrDefault().ConfigurationValue;
                        service.Credentials = new WebCredentials(SPUserName, SPPassword, SPDomain);
                        service.UseDefaultCredentials = false;
                        service.AutodiscoverUrl(SPAutodiscoverUrl);
                        SharedMailbox = new FolderId(WellKnownFolderName.Inbox, SPEmail);
                        itemView = new ItemView(Convert.ToInt32(DbContext.EmailApprovalsConfigurations.Where(p => p.ConfigurationKey == "SPEmailCount").FirstOrDefault().ConfigurationValue));
                    }
                    else
                    {
                        string FaxUserName = DbContext.EmailApprovalsConfigurations.Where(p => p.ConfigurationKey == "FaxEmailUserName").FirstOrDefault().ConfigurationValue;
                        string FaxPassword = DbContext.EmailApprovalsConfigurations.Where(p => p.ConfigurationKey == "FaxEmailPassword").FirstOrDefault().ConfigurationValue;
                        string FaxDomain = DbContext.EmailApprovalsConfigurations.Where(p => p.ConfigurationKey == "FaxEmailDomain").FirstOrDefault().ConfigurationValue;
                        string FaxAutodiscoverUrl = DbContext.EmailApprovalsConfigurations.Where(p => p.ConfigurationKey == "FaxEmailAutoDiscoverUrl").FirstOrDefault().ConfigurationValue;
                        string FaxEmail = DbContext.EmailApprovalsConfigurations.Where(p => p.ConfigurationKey == "FaxCallCenterEmail").FirstOrDefault().ConfigurationValue;
                        service.Credentials = new WebCredentials(FaxUserName, FaxPassword, FaxDomain);
                        service.UseDefaultCredentials = false;
                        service.AutodiscoverUrl(FaxAutodiscoverUrl);
                        SharedMailbox = new FolderId(WellKnownFolderName.Inbox, FaxEmail);
                        itemView = new ItemView(Convert.ToInt32(DbContext.EmailApprovalsConfigurations.Where(p => p.ConfigurationKey == "FaxEmailCount").FirstOrDefault().ConfigurationValue));
                    }
                    var Email = service.FindItems(SharedMailbox, itemView).Where(p => p.Id.UniqueId == AutoGeneratedEmailId).FirstOrDefault();
                    EmailMessage message = EmailMessage.Bind(service, (EmailMessage.Bind(service, Email.Id)).Id, new PropertySet(BasePropertySet.FirstClassProperties, new ExtendedPropertyDefinition(0x1013, MapiPropertyType.Binary)));
                    if (IsClosed == true)
                    {
                        message.Flag.FlagStatus = ItemFlagStatus.Complete;
                        message.Flag.CompleteDate = DateTime.Now;
                        message.Update(ConflictResolutionMode.AlwaysOverwrite);
                    }
                    else
                    {
                        message.IsRead = true;
                        message.Flag.FlagStatus = ItemFlagStatus.Flagged;
                        message.Flag.StartDate = DateTime.Now;
                        message.Flag.DueDate = DateTime.Now;
                        message.Update(ConflictResolutionMode.AlwaysOverwrite);
                    }
                    return true;
                }
            }
            catch (Exception ex)
            {
                return false;
            }
        }
    }
}