//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BNC.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BNCEntities : DbContext
    {
        public BNCEntities()
            : base("name=BNCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuditCategoryDIM> AuditCategoryDIMs { get; set; }
        public virtual DbSet<AuditFlow> AuditFlows { get; set; }
        public virtual DbSet<AuditFlowBatchDetail> AuditFlowBatchDetails { get; set; }
        public virtual DbSet<AuditFlowDetail> AuditFlowDetails { get; set; }
        public virtual DbSet<BatchAuditingRequest> BatchAuditingRequests { get; set; }
        public virtual DbSet<BatchClosingRequest> BatchClosingRequests { get; set; }
        public virtual DbSet<BatchingFilterationDetail> BatchingFilterationDetails { get; set; }
        public virtual DbSet<BatchingRequest> BatchingRequests { get; set; }
        public virtual DbSet<ClaimsActCategoryDIM> ClaimsActCategoryDIMs { get; set; }
        public virtual DbSet<ClosedBatchReAdministrationRequest> ClosedBatchReAdministrationRequests { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<DataEntryAdminstrationRequest> DataEntryAdminstrationRequests { get; set; }
        public virtual DbSet<DataEntryBatchAssigningRequest> DataEntryBatchAssigningRequests { get; set; }
        public virtual DbSet<FilterationCategoriesDIM> FilterationCategoriesDIMs { get; set; }
        public virtual DbSet<FilterationRequest> FilterationRequests { get; set; }
        public virtual DbSet<FilterationRequestDetail> FilterationRequestDetails { get; set; }
        public virtual DbSet<FinancialAuditRequest> FinancialAuditRequests { get; set; }
        public virtual DbSet<MedicalAuditRequest> MedicalAuditRequests { get; set; }
        public virtual DbSet<MIAuditRequest> MIAuditRequests { get; set; }
        public virtual DbSet<Provider> Providers { get; set; }
        public virtual DbSet<ProviderAddress> ProviderAddresses { get; set; }
        public virtual DbSet<ReconciliationAuditRequest> ReconciliationAuditRequests { get; set; }
        public virtual DbSet<ReleaseActionDIM> ReleaseActionDIMs { get; set; }
        public virtual DbSet<StatusDIM> StatusDIMs { get; set; }
        public virtual DbSet<SystemDIM> SystemDIMs { get; set; }
        public virtual DbSet<SystemEntitiesDIM> SystemEntitiesDIMs { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<TransferReasonDIM> TransferReasonDIMs { get; set; }
        public virtual DbSet<TransferRequestHistory> TransferRequestHistories { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<ReceivingRequest> ReceivingRequests { get; set; }
    }
}
