//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BNC.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilterationCategoriesDIM
    {
        public int FilterationCategoriesID { get; set; }
        public int ClaimsActCategoryFK { get; set; }
        public int CompanyFK { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public Nullable<System.DateTime> DeletionDate { get; set; }
    
        public virtual ClaimsActCategoryDIM ClaimsActCategoryDIM { get; set; }
        public virtual Company Company { get; set; }
    }
}
