//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BNC.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferRequestHistory
    {
        public int TransferRequestHistoryID { get; set; }
        public Nullable<int> FilterationRequestFK { get; set; }
        public Nullable<int> RequestTypeFK { get; set; }
        public Nullable<int> TransferedByPersonFK { get; set; }
        public Nullable<System.DateTime> TransferedOnDate { get; set; }
        public string TransferedComment { get; set; }
        public Nullable<int> TransferedToTeamFK { get; set; }
        public Nullable<int> TransferedToPersonFK { get; set; }
        public Nullable<int> TransferReasonFK { get; set; }
        public Nullable<int> AssignedByFK { get; set; }
        public Nullable<System.DateTime> AssignedOnDate { get; set; }
        public Nullable<int> ReleaseActionFK { get; set; }
        public string ReleaseActionDetails { get; set; }
        public string ReleaseActionComment { get; set; }
        public Nullable<System.DateTime> ReleasedOnDate { get; set; }
        public Nullable<int> StatusFK { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public Nullable<System.DateTime> DeletionDate { get; set; }
    
        public virtual ReleaseActionDIM ReleaseActionDIM { get; set; }
        public virtual StatusDIM StatusDIM { get; set; }
        public virtual Team Team { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
