//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestHoursHandler
    {
        public int RequestHoursHandlerID { get; set; }
        public Nullable<int> UserFK { get; set; }
        public Nullable<int> RequestHandlerFK { get; set; }
        public Nullable<int> RequestFK { get; set; }
        public Nullable<System.TimeSpan> StartOffHour { get; set; }
        public Nullable<System.TimeSpan> EndOffHour { get; set; }
        public Nullable<decimal> Duration { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public Nullable<System.DateTime> DeletionDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual RequestHandler RequestHandler { get; set; }
        public virtual Request Request { get; set; }
    }
}
