<%@ Page ValidateRequest="false" Title="" Language="C#" MasterPageFile="~/MasterPages/MasterPage.Master" EnableEventValidation="false" AutoEventWireup="true" CodeBehind="OpenAutoGenerated.aspx.cs" Inherits="CallCenterNotesApp.Portal.OpenAutoGenerated" Async="true" %>

<%@ Register Assembly="FreeTextBox" Namespace="FreeTextBoxControls" TagPrefix="FTB" %>


<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolderHeader" runat="server">
    <div class="row">
        <div class="col-md-12">
            <!--breadcrumbs start -->
            <ul class="breadcrumb">
                <li><a href="#"><i class="fa fa-home"></i>Home</a></li>
                <li><a href="#">Add New Email Request</a></li>
            </ul>
            <!--breadcrumbs end -->
        </div>
    </div>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolderBody" runat="server">
    <!-- Main content -->
    <!--row1-->
    <div class="alert alert-danger alert-dismissable" runat="server" id="div_Error">
        Email Request Is Not Added , Please Verify Inputs
    </div>
    <div class="alert alert-success alert-dismissable" runat="server" id="div_Success">
        Your Email Request Submitted Successfully
    </div>
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <section class="panel">
                    <header class="panel-heading">Request Details </header>
                    <div class="panel-body">
<%--                        <form class="form-horizontal tasi-form" role="form" runat="server">--%>
                            <asp:Label ID="FaxLable" Font-Bold="true" Font-Size="Large" ForeColor="Red" runat="server">Attention: This Request Is a FAX</asp:Label>
                            <div style="padding-left: 270px; padding-bottom: 5px">
                            </div>
                            <div class="col-sm-12" align="Center">
                                <label id="TicketNumber" runat="server" style="font-size: 38px; padding-bottom: 15px ;color:goldenrod">3290</label>
                            </div>

                            <div class="form-group" style="font-weight: bold; font-size: large; color: darkcyan">

                                <label runat="server" id="RequestTypeLabel" class="col-sm-2 col-sm-2 control-label">Request Type<label style="color: red">*</label></label>
                                <div class="col-sm-3">
                                    <asp:DropDownList runat="server" ID="Dropdownlist1" Width="248px" Height="45px" OnSelectedIndexChanged="Dropdownlist1_SelectedIndexChanged" AutoPostBack="True">
                                        <asp:ListItem Text="Select Request Type " Value="-1"></asp:ListItem>
                                        <asp:ListItem Value="1">General</asp:ListItem>
                                        <asp:ListItem Value="2">Special</asp:ListItem>
                                        <asp:ListItem Value="3">Inquiry</asp:ListItem>
                                        <asp:ListItem Value="4">None</asp:ListItem>
                                    </asp:DropDownList>
                                    <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server"
                                        ValidationGroup="SubmitValidation" ErrorMessage="Request Type Is Required" ForeColor="Red" InitialValue="-1"
                                        ControlToValidate="Dropdownlist1" Display="Dynamic">
                                    </asp:RequiredFieldValidator>
                                </div>
                                <label class="col-sm-2 col-sm-2 control-label">Medical ID<label style="color: red">*</label></label>
                                <div class="col-sm-3">
                                    <input type="text" class="form-control input-lg m-b-10" id="MedicalID" runat="server">
                                    <asp:RequiredFieldValidator ValidationGroup="SubmitValidation" ID="MedicalIDValidator" runat="server" ErrorMessage="Medical ID Is Required" ControlToValidate="MedicalID" ForeColor="Red"></asp:RequiredFieldValidator><br />
                                    <asp:RegularExpressionValidator ID="RegularExpressionValidator1" runat="server" ControlToValidate="MedicalID" ErrorMessage="Please Enter Only Numbers" ForeColor="Red" ValidationExpression="^\d+$"></asp:RegularExpressionValidator>
                                </div>



                            </div>
                            <div class="form-group" style="font-weight: bold; font-size: large; color: darkcyan">
                                <label class="col-sm-2 col-sm-2 control-label">Subject<label style="color: red">*</label></label>
                                <div class="col-sm-8">
                                    <input type="text" class="form-control input-lg m-b-10" id="MailSubject" runat="server" readonly>
                                </div>
                            </div>

                            <div class="form-group" style="font-weight: bold; font-size: large; color: darkcyan">


                                <label class="col-sm-2 col-sm-2 control-label">Approval Category<label style="color: red">*</label></label>


                                <div class="col-sm-3">
                                    <asp:DropDownList runat="server" ID="Category" Width="248px" Height="45px">
                                        <asp:ListItem Text="Select Category " Value="-1"></asp:ListItem>
                                        <asp:ListItem Text="Inpatient" Value="1"></asp:ListItem>
                                        <asp:ListItem Text="Outpatient" Value="2"></asp:ListItem>
                                        <asp:ListItem Text="Medication" Value="3"></asp:ListItem>

                                    </asp:DropDownList>
                                    <asp:RequiredFieldValidator ID="CategoryValidation" runat="server"
                                        ValidationGroup="SubmitValidation" ErrorMessage="Request Category Is Required" ForeColor="Red" InitialValue="-1"
                                        ControlToValidate="Category" Display="Dynamic">
                                    </asp:RequiredFieldValidator>
                                </div>
                                <label class="col-sm-2 col-sm-2 control-label">Priority<label style="color: red">*</label></label>
                                <div class="col-sm-3">
                                    <asp:DropDownList runat="server" ID="Priority" Width="248px" Height="45px">
                                        <asp:ListItem Text="Select Priority" Value="-1"></asp:ListItem>
                                        <asp:ListItem Text="Normal" Value="1"></asp:ListItem>
                                        <asp:ListItem Text="High" Value="2"></asp:ListItem>
                                        <asp:ListItem Text="Emergency" Value="3"></asp:ListItem>

                                    </asp:DropDownList>
                                    <asp:RequiredFieldValidator ID="PriorityValidation" runat="server"
                                        ValidationGroup="SubmitValidation" ErrorMessage="Request Priority Is Required" ForeColor="Red" InitialValue="-1"
                                        ControlToValidate="Priority" Display="Dynamic">
                                    </asp:RequiredFieldValidator>
                                </div>


                            </div>

                            <div class="form-group" style="font-weight: bold; font-size: large; color: darkcyan">

                                <label class="col-sm-2 col-sm-2 control-label">Member Name</label>
                                <div class="col-sm-3">
                                    <input type="text" class="form-control input-lg m-b-10" id="MemberName" runat="server">
                                </div>
                                <label class="col-sm-2 col-sm-2 control-label">Client Name</label>
                                <div class="col-sm-3">
                                    <input type="text" class="form-control input-lg m-b-10" id="ClientName" runat="server">
                                </div>
                            </div>

                            <div class="form-group" style="font-weight: bold; font-size: large; color: darkcyan">

                                <label class="col-sm-2 col-sm-2 control-label">Provider Name</label>
                                <div class="col-sm-3">
                                    <input type="text" class="form-control input-lg m-b-10" id="ProviderName" runat="server">
                                </div>
                                <label class="col-sm-2 col-sm-2 control-label">Creation Date</label>
                                <div class="col-sm-3">
                                    <input type="text" class="form-control input-lg m-b-10" disabled id="CreationDate" runat="server">
                                </div>


                            </div>
                            <div class="form-group" style="font-weight: bold; font-size: large; color: darkcyan">

                                <label class="col-sm-2 col-sm-2 control-label">Email Source</label>
                                <div class="col-sm-3">
                                    <input type="text" class="form-control input-lg m-b-10" id="MailSource" runat="server">
                                </div>
                                      <label class="col-sm-2 col-sm-2 control-label">Close  Time </label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control input-lg m-b-10" id="CloseTime" runat="server" disabled>
                                    </div>
                            </div>
                              <div class="form-group" style="font-weight: bold; font-size: large; color: darkcyan">

                                   <label runat="server" id="RequestType2" class="col-sm-2 col-sm-2 control-label">Request Type<label style="color: red">*</label></label>
                                <div class="col-sm-3">
                                    <asp:DropDownList runat="server" ID="FaxTicketsType" Width="248px" Height="45px">
                                        <asp:ListItem Text="Select Request Type " Value="-1"></asp:ListItem>
                                        <asp:ListItem Value="1">General</asp:ListItem>
                                        <asp:ListItem Value="2">Special</asp:ListItem>
                                   
                                    </asp:DropDownList>
                                    <asp:RequiredFieldValidator ID="RequiredFieldValidator3" runat="server"
                                        ValidationGroup="SubmitValidation" ErrorMessage="Request Type Is Required" ForeColor="Red" InitialValue="-1"
                                        ControlToValidate="FaxTicketsType" Display="Dynamic">
                                    </asp:RequiredFieldValidator>
                                </div>

                                 </div>


                            <div class="form-group" style="font-weight: bold; font-size: large; color: darkcyan">
                                <label class="col-sm-2 col-sm-2 control-label">Body<label style="color: red">*</label></label>
                                <div class="col-sm-8">
                                    <FTB:FreeTextBox OnSaveClick="CallcenterOpenNote_SaveClick" ID="CallcenterOpenNote" runat="server" Height="280px" Width="100%" BackColor="237, 237, 237" ButtonSet="OfficeMac" EditorBorderColorDark="237, 237, 237" EditorBorderColorLight="237, 237, 237" GutterBackColor="237, 237, 237" GutterBorderColorDark="237, 237, 237" GutterBorderColorLight="237, 237, 237" OnTextChanged="CallcenterOpenNote_TextChanged" EnableHtmlMode="False">
                                    </FTB:FreeTextBox>
                                    <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server"
                                        ErrorMessage="Notes Is Required" ForeColor="Red" InitialValue="-1"
                                        ControlToValidate="CallcenterOpenNote" Display="Dynamic">
                                    </asp:RequiredFieldValidator>
                                </div>


                            </div>

                            <div class="row">
                                <label class="col-sm-3 col-sm-3 control-label" style="margin-right: 0px">Attachments<label style="color: red">*</label></label>
                                <div class="col-sm-3">
                                    <div class="form-group" id="TicketAttachmentTable" runat="server">
                                        <asp:ListView runat="server" ID="TicketAttachment">
                                            <ItemTemplate>
                                                <br />
                                              <button id="cook" runat="server" onserverclick="DeleteAttachment_Click" style="all: unset;" AttachmentID='<%#Eval("ID")%>' isDeleted="False">
                                                  <span class="btn btn-danger fa fa-times"></span>
                                                  
                                              </button>
<%--         <asp:Button ID="DeleteAttachment" isDeleted="False" AttachmentID='<%#Eval("ID")%>' runat="server" OnClick="DeleteAttachment_Click" Text="Button"  />--%>
<%--                                                <input id="cook" type="button" runat="server" onserverclick="DeleteAttachment_Click" AttachmentID='<%#Eval("ID")%>' isDeleted="False"/>--%>
                                                &nbsp &nbsp
         <asp:LinkButton ID="LinkButton2" OnClick="LinkButton2_Click"
             Path='<%#Eval("Path")%>' FileName='<%#Eval("Name") %>'
             runat="server"> <%#Eval("Name") %></asp:LinkButton>

                                                <%-- <div class="btn-group btn-group-xs">
													          <a data-toggle="tooltip" href="CcEmailRequestManageRequest.aspx?id=<%#Eval("ID")%>" title="Edit" class="btn btn-default"><i class="fa fa-edit"></i></a>
													        </div>--%>
                                                    </nsfare>
                                            </ItemTemplate>

                                        </asp:ListView>
                                    </div>
                                    <br />
                                    <asp:FileUpload ID="FileUpload1" runat="server" AllowMultiple="true" class="btn btn-default" />
                                </div>

<%--  --%>

                            </div>

                            <br />
                            <div style="margin-left: 40%">
                                <button type="submit" validationgroup="SubmitValidation" class="btn btn-primary" id="btn_Submit" onserverclick="btn_Submit_ServerClick" runat="server">Submit Request</button>
                                <button id="CloseBtn" runat="server" onserverclick="CloseBtn_ServerClick" class="btn btn-warning" type="submit">
                                    Close
                                </button>
                                <button id="IgnoreBtn" runat="server" onserverclick="IgnoreBtn_ServerClick" class="btn btn-warning" type="submit">
                                    Ignore
                                </button>

                                <button id="AssignBtn" runat="server" onserverclick="Assignclick" class="btn btn-primary" type="submit" validationgroup="Assign">
                                    Assign
                                </button>
                                <button type="submit" id="SaveAttached" runat="server" validationgroup="SubmitValidation" onserverclick="SaveAttached_ServerClick" class="btn btn-primary" >
                                    Save
                                </button>



                            </div>
                            <br />


                            <div class="col-md-12" style="text-align: center; top: 0px; left: -1px;">
                                <div class="toolbar-btn-action">
                                </div>
                                <div runat="server" id="ApproveOrRejectDiv">

                                    <div style="margin-top: 5px; margin-bottom: 5px; height: 2px; width: 100%; border-top: 1px solid gray;"></div>
                                    <header class="panel-heading" runat="server" id="header" style="margin-bottom: 15px">
                                        <h4>Inquiry Reply</h4>
                                    </header>
                                    <div class="col-md-12">

                                        <div class="form-group" id="Div11" runat="server">
                                            <div class="col-sm-3">
                                                <asp:RadioButtonList ID="RadioButtonList" CssClass="hiddenclass" runat="server">
                                                    <asp:ListItem Value="1">Normal Client</asp:ListItem>
                                                    <asp:ListItem Value="2">Special Client</asp:ListItem>
                                                </asp:RadioButtonList>
                                                <asp:RequiredFieldValidator ID="RadioButtonListValidation" runat="server"
                                                    ControlToValidate="RadioButtonList" ValidationGroup="SubmitToValidation" ErrorMessage="Select Type" Display="Dynamic"
                                                    ForeColor="Red"></asp:RequiredFieldValidator>
                                            </div>
                                            <br />
                                            <div class="col-sm-9">
                                                <FTB:FreeTextBox ID="OperatorNote" runat="server" Height="280px" Width="100%" BackColor="237, 237, 237" ButtonSet="OfficeMac" EditorBorderColorDark="237, 237, 237" EditorBorderColorLight="237, 237, 237" GutterBackColor="237, 237, 237" GutterBorderColorDark="237, 237, 237" GutterBorderColorLight="237, 237, 237" AllowHtmlMode="False" EnableHtmlMode="False">
                                                </FTB:FreeTextBox>
                                            </div>
                                             <div class="row">
                                <label class="col-sm-3 col-sm-3 control-label" style="margin-right: 0px">Attachments<label style="color: red">*</label></label>
                                <div class="col-sm-3">
                                                  <asp:ListView runat="server" ID="InquiryAttach">
                                            <ItemTemplate>
                                              &nbsp &nbsp
                                    <asp:LinkButton ID="LinkButton2" OnClick="LinkButton2_Click"
                                       Path='<%#Eval("Path")%>' FileName='<%#Eval("Name") %>'
                                        runat="server"> <%#Eval("Name") %></asp:LinkButton>

                                                <%-- <div class="btn-group btn-group-xs">
													          <a data-toggle="tooltip" href="CcEmailRequestManageRequest.aspx?id=<%#Eval("ID")%>" title="Edit" class="btn btn-default"><i class="fa fa-edit"></i></a>
													        </div>--%>
                                                    </nsfare>
                                            </ItemTemplate>

                                        </asp:ListView>
                                    </div></div>

                                        </div>
                                    </div>
                                    <div class="row" runat="server" id="EmailDetailsDiv">
                                        <div class="col-md-8" style="border-right: solid; border-right-color: gainsboro">
                                            <div class="row">
                                                <label class="col-sm-8 col-sm-8 control-label">Add/Update Email Receipts</label>
                                            </div>
                                            <br />

                                            <div class="row">
                                                <div class="col-md-4">
                                                    <asp:ListView ID="AddToList" runat="server" ShowFooter="true"
                                                        AutoGenerateColumns="false" OnSelectedIndexChanged="receiveEmail_SelectedIndexChanged" OnSelectedIndexChanging="receiveEmail_SelectedIndexChanging">
                                                        <ItemTemplate>
                                                            <div style="margin-bottom: 5px">
                                                                <asp:Button ID="RowNumber" CommandName="select" order='<%#Eval("ID") %>' Text='<%#Eval("ID") %>' runat="server" CssClass="btn btn-danger" />
                                                                <asp:TextBox ValidationGroup="SubmitValidation" ID="TextBox1" Text='<%#Eval("Email") %>' runat="server"></asp:TextBox>
                                                                <%--                        <asp:TextBox ID="TextBox2" Text='<%#Eval("Column2") %>' runat="server"></asp:TextBox>--%>
                                                                <asp:RequiredFieldValidator ValidationGroup="SubmitValidation"
                                                                    ID="RequiredFieldValidator2" runat="server"
                                                                    ErrorMessage="reqired" ForeColor="Red"
                                                                    ControlToValidate="TextBox1" Display="Dynamic"> 
                                                                </asp:RequiredFieldValidator>
                                                                <asp:RegularExpressionValidator ValidationGroup="SubmitValidation"
                                                                    ID="RegularExpressionValidator4" runat="server" ForeColor="Red"
                                                                    ControlToValidate="TextBox1" ErrorMessage="enter Valid Mail"
                                                                    ValidationExpression="\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*"></asp:RegularExpressionValidator>


                                                            </div>
                                                        </ItemTemplate>
                                                    </asp:ListView>
                                                    <br />
                                                    <asp:Button ID="Button1" runat="server" Text="Add To Receipt" OnClick="ADDreceiveofEmail" CssClass="btn btn-default" />
                                                </div>
                                                <div class="col-md-4">


                                                    <asp:ListView ID="AddCcList" runat="server" ShowFooter="true" AutoGenerateColumns="false" OnSelectedIndexChanging="InCC_SelectedIndexChanging">
                                                        <ItemTemplate>
                                                            <div style="margin-bottom: 5px">
                                                                <asp:Button ID="RowNumber" CommandName="select" order='<%#Eval("ID") %>' Text='<%#Eval("ID") %>' runat="server" CssClass="btn btn-danger" />
                                                                <asp:TextBox ID="TextBox1" Text='<%#Eval("Email") %>' runat="server"></asp:TextBox>
                                                                <%--                        <asp:TextBox ID="TextBox2" Text='<%#Eval("Column2") %>' runat="server"></asp:TextBox>--%>
                                                                <asp:RegularExpressionValidator ValidationGroup="SubmitValidation"
                                                                    ID="RegularExpressionValidator4" runat="server" ForeColor="Red"
                                                                    ControlToValidate="TextBox1" ErrorMessage="enter Valid Mail"
                                                                    ValidationExpression="\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*"></asp:RegularExpressionValidator>


                                                            </div>
                                                        </ItemTemplate>
                                                    </asp:ListView>

                                                    <asp:Button ID="Button2" runat="server" Text="Add Cc Receipt" OnClick="ADDInCCofEmailclick" CssClass="btn btn-default" />
                                                </div>
                                                <div class="col-md-4">

                                                    <asp:ListView ID="AddBccList" runat="server" ShowFooter="true" AutoGenerateColumns="false" OnPagePropertiesChanging="InBCC_PagePropertiesChanging" OnSelectedIndexChanging="InBCC_SelectedIndexChanging">
                                                        <ItemTemplate>
                                                            <div style="margin-bottom: 5px">
                                                                <asp:Button ID="RowNumber" CommandName="select" order='<%#Eval("ID") %>' Text='<%#Eval("ID") %>' runat="server" CssClass="btn btn-danger" />
                                                                <asp:TextBox ID="TextBox1" Text='<%#Eval("Email") %>' runat="server"></asp:TextBox>
                                                                <%--                        <asp:TextBox ID="TextBox2" Text='<%#Eval("Column2") %>' runat="server"></asp:TextBox>--%>
                                                                <asp:RegularExpressionValidator ValidationGroup="SubmitValidation"
                                                                    ID="RegularExpressionValidator4" runat="server" ForeColor="Red"
                                                                    ControlToValidate="TextBox1" ErrorMessage="enter Valid Mail"
                                                                    ValidationExpression="\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*"></asp:RegularExpressionValidator>
                                                            </div>
                                                        </ItemTemplate>
                                                    </asp:ListView>
                                                    <br />
                                                    <asp:Button ID="Button3" runat="server" Text="Add Bcc Receipt" OnClick="ADDInBCCofEmailclick" CssClass="btn btn-default" />
                                                </div>
                                            </div>

                                        </div>

                                        <div class="col-md-3" id="UploadFileDiv" runat="server" style="margin-left: 10px">
                                            <div class="row">
                                                <label class="col-sm-5 col-sm-5 control-label">Upload File(s) </label>
                                            </div>
                                            <br />
                                            <div class="row">
                                                <div class="form-group" id="ManagerApprovalTimeDiv" runat="server">
                                                    <div class="col-sm-2">
                                                        <asp:FileUpload ID="FileUpload2" AllowMultiple="true" runat="server" />


                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>


                                </div>

                            </div>


                            <div class="row">
                                <div class="col-md-12" style="text-align: center;">
                                    <br />
                                    <br />
                                    <div class="toolbar-btn-action">
                                        <button class="btn btn-success" runat="server" validationgroup="SubmitToValidation" onserverclick="ReplyBtn_ServerClick" id="ReplyBtn">Reply</button>
                                    </div>
                                </div>
                            </div>
                            <br />
                    </div>
                    <br />
            </div>


<%--            </form>--%>
        </div>
    </section>
    </div>
        </div>
    </section>
    <!-- /.content -->
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolderScripts" runat="server">
</asp:Content>
